# Generated by Django 5.1.4 on 2024-12-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='ingredients',
            field=models.ManyToManyField(through='restaurant.RecipeRequirement', to='restaurant.ingredient'),
        ),
        migrations.AlterUniqueTogether(
            name='reciperequirement',
            unique_together={('menu_item', 'ingredient')},
        ),
    ]
